name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: 15 6 * * 0
  workflow_dispatch:
    inputs:
          environment:
            description: 'Environment type'
            type: environment
            required: true
            
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "name ${{github.event_name}}"
          echo "ref ${{github.ref}}"
      - uses: actions/checkout@v3.3.0
      - name: List files in the repository
        run: |
            echo "The repository ${{ github.repository }} files:"
            tree
  Test:
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - run: "echo Testing..."
  Load-test:
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: Load test
    steps:
      - run: "echo Testing..."
      - run: "sleep 15"
  Production:
    needs: [Test, Load-test]
    if: github.event.inputs.environment == 'Production'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo "Step 1 deploying..."
          sleep 10
      - run: |
          echo "Step 2 deploying..."
          sleep 10
      - run: |
          echo "Step 3 deploying..."
          sleep 10
      - run: |
          echo "Step 4 deploying..."
          sleep 10
      - run: |
          echo "Step 5 deploying..."
          sleep 10
      - run: bash hello.ps1
